// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJL8Wesz09P-AEhRxqCghHO4H9FsRrud4',
    appId: '1:528405471290:web:935d31c51018bcb75b1503',
    messagingSenderId: '528405471290',
    projectId: 'pablo-d0d87',
    authDomain: 'pablo-d0d87.firebaseapp.com',
    databaseURL: 'https://pablo-d0d87-default-rtdb.firebaseio.com',
    storageBucket: 'pablo-d0d87.appspot.com',
    measurementId: 'G-SWJZ0QSMPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe5xkX7lJetpuTcQS93d_4GFCw3pLPSsQ',
    appId: '1:528405471290:android:54c37e361de0aa1e5b1503',
    messagingSenderId: '528405471290',
    projectId: 'pablo-d0d87',
    databaseURL: 'https://pablo-d0d87-default-rtdb.firebaseio.com',
    storageBucket: 'pablo-d0d87.appspot.com',
  );
}
